### ISSUE TITLE
Apply automated validation pipelines for external dependencies

### ISSUE THREAD

**Issue by turnerrainer** [buerokratt/Test-Driven-Development#2]
AS InfoSec
I WANT automated pipelines to be applied for external dependencies
SO THAT vulnerabilities could be detected and fixes deployed ASAP

### Acceptance Criteria

- [ ] Separate GitHub Actions pipelines for all Components
- [ ] Separate GitHub Actions pipelines for all Modules
- [ ] Pipelines can be called out manually separately
- [ ] ~Pipelines can be called out manually to complete all pipelines one-by-one in a row~
- [ ] Pipelines are called out as scheduled cronjobs at `00:00` daily
- [ ] Pull requests are automatically created for all vulnerabilities and suggestions
- [ ] Configure pipelines per actual requirements of Components / Modules

#### Technical requirements

- [ ] GitHub Actions Snyk pipeline
- [ ] GitHub Actions SonarCloud pipeline
- [ ] GitHub Actions Dependabot pipeline

#### Scope

- [ ] All pipelines run on `dev` branch
- [ ] ~All pipelines run on `test` branch~
- [ ] ~All pipelines run on `stage` branch~
- [ ] ~All pipelines run on `main` branch~

##### Components

- [ ] https://github.com/buerokratt/Ruuter
- [ ] https://github.com/buerokratt/DataMapper
- [ ] https://github.com/buerokratt/Resql
- [ ] https://github.com/buerokratt/TIM
- [ ] ~https://github.com/buerokratt/Turvis~
- [ ] ~https://github.com/buerokratt/XTR~

##### Modules

- [ ] https://github.com/buerokratt/Chat-Widget
- [ ] https://github.com/buerokratt/Buerokratt-Chatbot
- [ ] https://github.com/buerokratt/Analytics-Module
- [ ] https://github.com/buerokratt/Service-Module
- [ ] https://github.com/buerokratt/Training-Module

### Setup Requirements

> _Input provided by @1AhmedYasser_

- [ ] [Snyk](https://snyk.io/) Bürokratt Account
- [ ] [Sonar Cloud](https://sonarcloud.io/login) Bürokratt Account

#### Github Secrets Requirements

<details>
<summary>SNYK_TOKEN</summary>

##### Required to authenticate with Snyk
  - Path: `User -> Account Settings-> General -> Auth Token`
  - Url: https://app.snyk.io/account
</details>

<details>
<summary>SONAR_TOKEN</summary>

##### Required to authenticate with Sonar Cloud
  - Path: `User -> Account Settings-> Security -> Generate Token`
  - Url: https://sonarcloud.io/account/security
</details>

<details>
<summary>SONAR_PROJECT_KEY</summary>

##### Project key used in sonar cloud workflow
  - Path: `Project -> Information`
  - Url: `https://sonarcloud.io/project/information?id=<Project Key>`
</details>

<details>
<summary>SONAR_ORGANIZATION</summary>

##### Organization key used in sonar cloud workflow
  - Path: `Project -> Information`
  - Url: `https://sonarcloud.io/project/information?id=<Project Key>`
</details>

###### Note: Disable Automatic Analysis in Sonar Cloud so it won't fail the workflow, (Project -> Administration -> Analysis Method)

**Comment by 1AhmedYasser** [comment]
Note: Ruuter Has a problem in compiling tests in Git Actions, waiting alar insight on it

**Comment by rasmusei** [comment]
Igor will solve this in a different way
