### ISSUE TITLE
Disable logging sensitive information in application logs

### ISSUE THREAD

**Issue by turnerrainer** [buerokratt/Test-Driven-Development#3]
AS AN Architect
I WANT logging sensitive information in application logs to be disabled in production environment
SO THAT it couldn't be used in case of data breach

### Acceptance Criteria

- [x] Appropriate settings deployed as part of deployment pipeline
- [x] Logs do not contain any `requests` data
- [x] Logs do not contain any `response` data

#### Scope

- [x] `test` environment
- [x] `stage` environment
- [x] `prod` environment

**Comment by varmoh** [comment]
Updated the readme's and commited the `ruuter` changes
Commits
dev branch:
https://github.com/buerokratt/NoOps/commit/9079472eb9976bdf6cf1af92102a8f8423e45769
https://github.com/buerokratt/NoOps/commit/07b4b7d19b279f9236815982c672ae88e51e1988
https://github.com/buerokratt/NoOps/commit/9b4130c327240caf0f2282d008f2e128521206e7
stage branch:
https://github.com/buerokratt/NoOps/commit/a7e00ee353900c9b113b3478a744fefd08509650
https://github.com/buerokratt/NoOps/commit/4613cfff6d6ac64528ade09387754513ed5cb6a8
https://github.com/buerokratt/NoOps/commit/9e2f40dd59599cbac0ff1003fe98cb5f9a80aab0

**Comment by turnerrainer** [comment]
Tested and deployed by @varmoh
